name: publish docker image

on:
  push:
    tags:
      - '*'

jobs:
  build_artifacts:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
      matrix:
        arch:
          - windows-amd64
          - macos-x86_64
          - macos-aarch64
          - linux-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull Image
        run: docker pull leocov/arduino-processing:latest

      - name: clean dist directory
        run: rm -rf /dist

      - name: export processing app
        run: |
          docker run --rm \
            -v "$(pwd)/processing_control:/build/processing_control" \
            -w /build \
            leocov/arduino-processing:latest \
            processing-java \
              --sketch=/build/processing_control \
              --output=/build/dist \
              --variant=${{ matrix.arch }} \
              --export

